### ISSUE TITLE
This error from codes or me?

### ISSUE THREAD

**Issue by saeedalsnfawy** [EthanC/Athena#2]
File "itemshop.py", line 24
    Log.Info(self, f "Delaying process start for {self.delay}s...")
                                                                 ^
SyntaxError: invalid syntax

**Comment by saeedalsnfawy** [comment]
This (^) under last " not Log

**Comment by EthanC** [comment]
Ensure you're using the right version of Python, 3.7, as per the [README](https://github.com/EthanC/Athena/blob/master/README.md).

**Comment by saeedalsnfawy** [comment]
python -v to check version right?

**Comment by saeedalsnfawy** [comment]
python3.7 --version
Python 3.7.4

**Comment by saeedalsnfawy** [comment]
You can help me?

**Comment by EthanC** [comment]
There shouldn't be a space between the `f` and first double quote `"`. Redownload the script and don't modify it.

**Comment by saeedalsnfawy** [comment]
Same Error

**Comment by saeedalsnfawy** [comment]
File "itemshop.py", line 24
    Log.Info(self, f"Delaying process start for {self.delay}s...")
                                                                ^
SyntaxError: invalid syntax

**Comment by saeedalsnfawy** [comment]
You have any discord server to talk easier?

**Comment by saeedalsnfawy** [comment]
i redownloaded all files and tried again and its same??
u going to help me?

**Comment by EthanC** [comment]
I've successfully ran the script on multiple systems with varying environments. All of the code is correct and the necessary instructions are provided in the README, I'm not quite sure what you've done wrong unfortunately.

**Comment by saeedalsnfawy** [comment]
i tried it on CentosOS 7.6 and Ubuntu 16 and Ubuntu  18
Still same error
