### ISSUE TITLE
api issue 

### ISSUE THREAD

**Issue by kr00m** [EthanC/Athena#3]
the api changed from ( https://fn.notofficer.de/api/shop ) to ( https://fortnite-api.com/shop/br ) and other things like the rarity they should be all in lower case letters

**Comment by Luc1412** [comment]
I wrote a fix. Checkout #4

**Comment by fortnite2019bs** [comment]
Could you use https://www.heroku.com/ to run the script without having to do it manually, or how do I do it?

**Comment by fortnite2019bs** [comment]
How to change the date inside the util.py file and change the date? To Spanish thank you very much !!!

https://i.imgur.com/Pw6lVcY.png

**Comment by Luc1412** [comment]
It's not related to that issue, but checkout https://www.tutorialspoint.com/python/time_strftime.htm there is explained how these formatters work

**Comment by EthanC** [comment]
Fixed in latest commit.

@fortnite2019bs I've added support for multilingual dates in the image/console, just set your language using the configuration file.
