### ISSUE TITLE
Bundle Support

### ISSUE THREAD

**Issue by kuletxcore** [EthanC/Athena#6]
Hello! i was wondering when the items that come in a bundle will get marked as a bundle instead of a duplicate skin, and will show the bundle name instead?

Thank you!

**Comment by kuletxcore** [comment]
![image](https://user-images.githubusercontent.com/4536676/73901457-ce02b180-48cd-11ea-9669-9deff6759859.png)
here's the shop for 02.06.2020 for example. Zadie is listed twice, and the actual name of the bundle in the shop is "Metal Masq Bundle".

**Comment by MyNameIsDark01** [comment]
It's an api problem. The bundle has another noun, but the api doesn't find it out at 00:00 GMT.
The api's admin edit it later.
