### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by itsborck** [EthanC/Athena#8]
In the itemshop.py file I get an error saying Unable to import 'coloredlogs', Unable to import 'twitter', Unable to import 'PIL'. I also get Unable to import 'requests' and Unable to import 'PIL'. I don't know if I forgot to install something or if something is wrong.
Thanks in advance!

**Comment by EthanC** [comment]
Please read the README. You're missing the required packages, you can learn how to install these elsewhere.
